### PR TITLE
added http://blog.crashdump.io/tag/erlang.html feed

### PR DESCRIPTION
**Pull request by d1ffuz0r**
Hi,

We added generating rss feed for Erlang (actually any) tag on our blog. https://twitter.com/stevenproctor/status/552840430463614976

Thank you!

### CODE REVIEW

**Comment by stevenproctor** [comment]
Thanks so much!

**Comment by stevenproctor** [comment]
Should go live around the hour change. :smiley:

**Comment by stevenproctor** [comment]
It is now live!

**Comment by d1ffuz0r** [comment]
Thank you!

**Pull request merged**
